### ISSUE TITLE
Where can I get TICKER.csv ?

### ISSUE THREAD

**Issue by ucasiggcas** [mohabmes/StockNN#4]
Dear,
In the RNN py [file](https://github.com/mohabmes/StockNN/blob/master/RNN/rnn-stock.py),
I know the dataset is all in the [link](https://github.com/mohabmes/pystocklib)
But there is only AAPL.csv,No TICKER.csv
So how to get the TICKER.csv
Could U help me,Please?
Thx

**Comment by mohabmes** [comment]
Hi @ucasiggcas 

'TICKER.csv' is just a placeholder for the real filename. (ex. Replace it with 'AAPL.csv')

A ticker is an abbreviation used to uniquely identify publicly traded shares of a particular stock on a particular stock market. (ex. Apple [ticker symbol: AAPL])

To download the historical data & create the csv file use:
`hist = HistoricalData('AAPL', from_date=[2011, 1, 25], to_date=[2018, 3, 13])`
`hist.create_csv()`
